# Default values for pg-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

Namespace: &namespace sandbox

Project:
  Name: data

image:
  Name: postgres
  Tag: 11

service:
  type: NodePort
  port: 5432

Port:
  Container: 5432
  Service: 5432
  NodePort: 31132

Postgres:
  db: database
  user: admin
  password: jw8s0F4

Labels:
  Name: data-test

resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    memory: 256Mi
    cpu: 500m
