apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Labels.Name }}
  namespace: {{ .Values.Namespace | default "default" }}
  labels:
    app: {{ .Values.Labels.Name }}
spec:
  type: {{ .Values.service.type}}
  ports:
    - name: {{ .Values.Labels.Name }}
      port: {{ .Values.Port.Service}}
      targetPort: {{ .Values.Port.Container}}
      nodePort: {{ .Values.Port.NodePort}}
      protocol: TCP 
  selector:
   app: {{ .Values.Labels.Name }}